### ISSUE TITLE
Nejede na 4.2.2

### ISSUE THREAD

**Issue by tenondra** [autisti/QReadeR#2]
Jenom FYI Adamovi to nejede na 4.2.2.

**Comment by zl0bit** [comment]
wut

**Comment by zl0bit** [comment]
Adam má s8, takže určitě oreo

**Comment by tenondra** [comment]
Hrbotickymu

**Comment by zl0bit** [comment]
ajo

**Comment by zl0bit** [comment]
kdy to říkal

**Comment by zl0bit** [comment]
Bude fix dnes, potřeba snížit minimální požadovanou verzi SDK z 18 (4.3) na 17 (4.2).
